python main.py \
  --savedir './results/run_mimgnet_5way1shot_lowlr_goodinit' \
  --dataset 'mimgnet' \
  --mode 'train' \
  --gpu_num 7 \
  --alpha 0.01 \
  --metabatch 4 \
  --n_steps 5 \
  --way 5 \
  --shot 1 \
  --query 15 \
  --meta_lr 1e-4
